#theme: jekyll-theme-leap-day
remote_theme: vicariousdrama/nodeyez
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
#  parse_block_html: true
title: NODEYEZ - Display panels to get the most from your Bitcoin node
description: Display panels and scripts to get the most from your Bitcoin node
url: https://nodeyez.com
#baseurl: /nodeyez
twitter_username: vicariousdrama
header_image: /images/nodeyez.svg
collections:
  docs:
    output: true
    permalink: /docs/:path
    order:
      - index.md
      - script-ipaddress.md
      - script-sysinfo.md
      - script-utcclock.md
      - script-arthashdungeon.md
      - script-arthash.md
      - script-blockheight.md
      - script-difficultyepoch.md
      - script-halving.md
      - script-inscriptionmempool.md
      - script-mempoolblocks.md
      - script-opreturn.md
      - script-ordinals.md
      - script-channelbalance.md
      - script-channelfees.md
      - script-lndhub.md
      - script-rofstatus.md
      - script-f2pool.md
      - script-luxor-mining-hashrate.md
      - script-minerbraiins.md
      - script-minermicrobt.md
      - script-slushpool.md
      - script-nodeyezdual.md
      - script-fearandgreed.md
      - script-fiatprice.md
      - script-satsperusd.md
      - script-whirlpoolclimix.md
      - script-whirlpoolliquidity.md
      - script-compassmininghardware.md
      - script-compassminingstatus.md
      - script-gasprice.md
      - script-raretoshi.md
      - script-daily-data-retrieval.md
      - config-collectapi.md
  install_steps:
    output: true
    permalink: /install_steps/:path
    order:
      - yournode.md
      - displayscreen.md
      - pythondeps.md
      - nodeyez.md
      - websitedashboard.md
      - runatstartup.md
include: [".well-known"]
