theme: jekyll-theme-leap-day
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
#  parse_block_html: true
description: Display panels to get the most from your node
header_image: /images/nodeyez.svg
include: [".well-known"]
