theme: jekyll-theme-leap-day
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
#  parse_block_html: true
title: NODEYEZ - Display panels to get the most from your Bitcoin node
description: Display panels and scripts to get the most from your Bitcoin node
url: https://nodeyez.com
baseurl: /nodeyez
twitter_username: vicariousdrama
header_image: /images/nodeyez.svg
collections:
  docs:
    output: true
    permalink: /docs/:path
  install_steps:
    output: true
    permalink: /install_steps/:path
    order:
      - install-1-raspberrypinode.md
      - install-2-displayscreen.md
      - install-3-pythondeps.md
      - install-4-nodeyez.md
      - install-5-websitedashboard.md
      - install-6-runatstartup.md
include: [".well-known"]
